language: php
php:
    - 7.2
    - 7.3
    - 7.4

script:
    - composer install

    # code standards
    - vendor/bin/phpcs --colors -ps

    # static analysis
    - vendor/bin/phpstan analyse src --level=max --ansi

    # Unit Tests
    - vendor/bin/phpunit --testdox --color=always

    # integration
    - .travis/integration
    - cd blog ; php artisan translator:update ; php integration.php


